version: "3.8"

# Services
services:
  # Nginx Service
  nginx:
    image: nginx:1.21
    volumes:
      - ./../src:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
    ports:
      - 80:80
    depends_on:
      - php

  # PHP Service
  php:
    build:
      context: ""
      dockerfile: ./php/Dockerfile
    working_dir: /var/www
    volumes:
      - ./../src:/var/www
      - ./php/conf.d:/usr/local/etc/php/conf.d
    depends_on:
      - mysql

  redis:
    image: redis:6.0
    ports:
      - 63790:6379
    hostname: redis
    volumes:
      - redis-data:/data

  #MySQL Service
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: pm
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql

  # PMA Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
volumes:
  redis-data:
  mysql-data:
